filters:
  artists:
    # Palavras chave para excluir artistas
    exclude_keywords:
      - Padre
      - Frei
      - Irmã
      - Católico
      - Católica
      - Ministério Católico
      - Santuário
      - Diocese
      - Sacerdote
      - Umbanda
      - Oxum
      - Axé
      - Paróquia
      - Mosteiro
      - Ogum

  titles:
    # Palavras chave para excluir títulos de músicas
    exclude_keywords:
      - Santa Maria
      - Sacramento
      - Exu
      - Axé
      - Orixá
      - Oxum
      - Umbanda
      - Candomblé
      - Ave Maria
      - Terço
      - Nossa Senhora
      - Santo Anjo
      - São Miguel
      - São Gabriel
      - São Rafael
      - Santíssimo
      - Eucaristia
      - Divino Pai Eterno
      - Sagrado Coração
      - Paróquia

  lyrics:
    # Configurações para filtro de letras
    language: pt  # Código da língua esperada
    min_length: 100  # Comprimento mínimo da letra (caracteres)
    max_length: 4000  # Comprimento máximo da letra (caracteres)