name: Full Scraping

on:
  workflow_dispatch:
    inputs:
      reason:
        description: 'Reason for running full scraping'
        required: true
        default: 'Manual full scraping run'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Prepare environment and set permissions
        run: |
          mkdir -p data
          sudo chown -R 1000:1000 .

      - name: Build and start services
        run: |
          docker compose build
          docker compose up -d
          sleep 10 # Aguarda containers iniciarem

      - name: Install dependencies
        run: |
          docker compose exec -T app poetry install

      - name: Initialize database
        run: |
          docker compose exec -T app poetry run python -m letras init
          
      - name: Run full scraping
        run: |
          docker compose exec -T app poetry run python -m letras full

      - name: Get current date
        id: date
        run: echo "date=$(date +'%d%m%Y')" >> $GITHUB_OUTPUT

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            data/*.zip
            data/*.sql
          body_path: data/RELEASE_NOTES.md
          name: Letras ${{ steps.date.outputs.date }}
          tag_name: v${{ steps.date.outputs.date }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        if: always()
        run: docker compose down --volumes